package com.group5.ArtExpress;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableAsync;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableAsync
public class ArtExpressApplication {

	public static void main(String[] args) {
		SpringApplication.run(ArtExpressApplication.class, args);
	}

}
